### ISSUE TITLE
Elapsed time stop

### ISSUE THREAD

**Issue by champioj** [generalfuzz/acrn#1]
Behaviour on Chrome 34:
The elapsed time stop when it's not in the current tab.

**Comment by KeeonTabrizi** [comment]
↑ I'm still seeing this as an issue, where the timer only elapses when the tab is in focus.

**Comment by KeeonTabrizi** [comment]
cc @generalfuzz

**Comment by Markussss** [comment]
@KeeonTabrizi Are you seeing the issue on the website or in the pull request? If it's in the pull request, I'll take a look at it. If it's on the website, however, we just have to wait until @generalfuzz decides to update the website with the pull request (or some other code he want to write instead).

**Comment by KeeonTabrizi** [comment]
@Markussss thanks for the details. I'm seeing it in the current website. I have not used what's in the pull request.

**Comment by generalfuzz** [comment]
I've updated w/ latest code - the issue is still present afaik

**Comment by PeterVermont** [comment]
Just wanted to confirm that this is working properly for me. Good fix.
